// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("2022MathMechFSharpLessons.Tests")>]
[<assembly: AssemblyProductAttribute("2022MathMechFSharpLessons")>]
[<assembly: AssemblyVersionAttribute("0.1.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2022-09-26T00:00:00.0000000+03:00")>]
[<assembly: AssemblyFileVersionAttribute("0.1.1")>]
[<assembly: AssemblyInformationalVersionAttribute("0.1.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","016d8a718f3816d90fcde0e0e93e8ebe25b89f31")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "2022MathMechFSharpLessons.Tests"
    let [<Literal>] AssemblyProduct = "2022MathMechFSharpLessons"
    let [<Literal>] AssemblyVersion = "0.1.1"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2022-09-26T00:00:00.0000000+03:00"
    let [<Literal>] AssemblyFileVersion = "0.1.1"
    let [<Literal>] AssemblyInformationalVersion = "0.1.1"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "016d8a718f3816d90fcde0e0e93e8ebe25b89f31"
